### ISSUE TITLE
thoughts on ember-cli-electron?

### ISSUE THREAD

**Issue by stefanpenner** [ghamha1n/ember-manager#1]
Just noticed this addon exists: https://www.npmjs.com/package/ember-cli-electron

might be nice to use that, or provide feedback to make it sufficient to use

**Comment by hamzahio** [comment]
@stefanpenner 

i add the addon and it is working fine see [#5c5a14e](https://github.com/ghamha1n/ember-manager/commit/b8ff19a15df89b7d0d42206c4d1f17621fad6c7b)

thanks
